<h1><center>LINEAR ALGEBRA</center></h1>

In [1]:
import numpy as np

# <a name='svmt'></a>Scalar, Vector, Matrix

## <a name='scalar'></a>Scalar

In [2]:
S = 8
print(S)

8


## <a name='vector'></a>Vector

In [3]:
V = np.array([[1,2,3,4,5,6,7,8,9]])
print(V.shape)
print(V)

(1, 9)
[[1 2 3 4 5 6 7 8 9]]


## <a name='matrix'></a>Matrix

In [4]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M.shape)
print(M)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# <a name='od'></a>Operasi Dasar pada Marix dan Vector

## <a name='tambah_kurang'></a>Penjumlahan dan Pengurangan pada Matrix dan Vector

In [5]:
V1 = np.array([[2,7,9]])
V2 = np.array([[5,7,3]])
penjumlahan_vector = V1+V2
pengurangan_vector = V1-V2

print(penjumlahan_vector)
print(pengurangan_vector)

[[ 7 14 12]]
[[-3  0  6]]


In [6]:
M1 = np.array([[2,7,9],[5,8,1]])
M2 = np.array([[4,1,6],[5,7,3]])
penjumlahan_matrix = M1+M2
pengurangan_matrix = M1-M2

print(penjumlahan_matrix)
print(pengurangan_matrix)

[[ 6  8 15]
 [10 15  4]]
[[-2  6  3]
 [ 0  1 -2]]


## <a name='transpose'></a>Transpose pada Matrix dan Vector

In [7]:
V1 = np.array([[2,7,9]])
V1_transpose = np.transpose(V1)
print(V1_transpose)

[[2]
 [7]
 [9]]


In [8]:
V1_transpose = V1.transpose()
print(V1_transpose)

[[2]
 [7]
 [9]]


In [9]:
M1 = np.array([[2,7,9],[5,8,1]])
M1_transpose = np.transpose(M1)
print(M1_transpose)

[[2 5]
 [7 8]
 [9 1]]


In [10]:
M1_transpose = M1.transpose()
print(M1_transpose)

[[2 5]
 [7 8]
 [9 1]]


## <a name='perkalian'></a>Perkalian pada Matrix dan Vector

In [11]:
V1 = np.array([[2,7,9]])
V2 = np.array([[5,7,3]])
perkalian_dalam = V1*V2
dot_product = V1.dot(V2.transpose())

print(perkalian_dalam,dot_product)

[[10 49 27]] [[86]]


In [12]:
M1 = np.array([[2,7,9],[5,8,1]])
M2 = np.array([[4,1,6],[5,7,3]])
perkalian_dalam = M1*M2
dot_product = M1.dot(M2.transpose())

print(perkalian_dalam,dot_product)

[[ 8  7 54]
 [25 56  3]] [[69 86]
 [34 84]]


# <a name='id'></a>Matrix Identitas dan Invers

## <a name='iden'></a>Matrix Identitas

In [13]:
#matrix identitas dengan n=3
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Determinan

In [14]:
a = np.array([[0,1,0], [0,0,1], [4,-17,8]])

In [15]:
np.linalg.det(a)

4.0

## <a name='inv'></a>Matrix Invers

In [16]:
M = np.array([[2,-1],[-1,1]]) 
M_inv = np.linalg.inv(M)
M

array([[ 2, -1],
       [-1,  1]])

In [19]:
# Manual
adj_M = np.array([[M[1][1],-1*M[0][1]], [-1*M[1][0],M[0][0]]])
det_M = np.linalg.det(M)
M_inv = (1/int(det_M)) * adj_M
M_inv

array([[1., 1.],
       [1., 2.]])

In [20]:
M.dot(M_inv)

array([[1., 0.],
       [0., 1.]])

## Solusi Sistem Persamaan

In [19]:
a = np.array([[1,1,2], [2,4,-3],[3,6,-5]])
b = np.array([9,1,0])
x = np.linalg.solve(a, b)
x

array([1., 2., 3.])

## Eigen

In [21]:
#Nilai eigen
a = np.array([[0,0,-2], [1,2,1],[1,0,3]])
np.linalg.eigvals(a)

array([2., 1., 2.])

In [22]:
# Vektor eigen
x = np.array([0,1,0])

a.dot(x) == 2*x

array([ True,  True,  True])